# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CICD for my project

on:
  push:
    branches: [ develop ]

jobs:
  cicd-covid19:
    runs-on: [ubuntu-latest]
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@octocat'
      - name: Config Github user
        run: |
          git config --global user.email "jose.chavarria16@gmail.com"
          git config --global user.name "JM"
      - name: NPM install dependencies
        run: npm install
      - name: NPM run build
        run: npm run build
        env:
          CI: true
      - name: NPM patch version
        run: npm version patch
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Publish to GitHub Packages
        run: npm publish
